config/routes.rb
Rails.application.routes.draw do
  resources :mslanes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mislane.rb
class Mislane < ApplicationRecord
end

app/models/mslane.rb
class Mslane < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mslanes_controller.rb
class MslanesController < ApplicationController
  before_action :set_mslane, only: [:show, :edit, :update, :destroy]

  # GET /mslanes
  # GET /mslanes.json
  def index
    @mslanes = Mslane.all
  end

  # GET /mslanes/1
  # GET /mslanes/1.json
  def show
  end

  # GET /mslanes/new
  def new
    @mslane = Mslane.new
  end

  # GET /mslanes/1/edit
  def edit
  end

  # POST /mslanes
  # POST /mslanes.json
  def create
    @mslane = Mslane.new(mslane_params)

    respond_to do |format|
      if @mslane.save
        format.html { redirect_to @mslane, notice: 'Mslane was successfully created.' }
        format.json { render :show, status: :created, location: @mslane }
      else
        format.html { render :new }
        format.json { render json: @mslane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mslanes/1
  # PATCH/PUT /mslanes/1.json
  def update
    respond_to do |format|
      if @mslane.update(mslane_params)
        format.html { redirect_to @mslane, notice: 'Mslane was successfully updated.' }
        format.json { render :show, status: :ok, location: @mslane }
      else
        format.html { render :edit }
        format.json { render json: @mslane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mslanes/1
  # DELETE /mslanes/1.json
  def destroy
    @mslane.destroy
    respond_to do |format|
      format.html { redirect_to mslanes_url, notice: 'Mslane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mslane
      @mslane = Mslane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mslane_params
      params.require(:mslane).permit(:Title, :Category, :Release, :Cost)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mslanes_helper.rb
module MslanesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Videosystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mslanes/_form.html.erb
<%= form_with(model: mslane, local: true) do |form| %>
  <% if mslane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mslane.errors.count, "error") %> prohibited this mslane from being saved:</h2>

      <ul>
      <% mslane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Title %>
    <%= form.text_field :Title %>
  </div>

  <div class="field">
    <%= form.label :Category %>
    <%= form.text_field :Category %>
  </div>

  <div class="field">
    <%= form.label :Release %>
    <%= form.number_field :Release %>
  </div>

  <div class="field">
    <%= form.label :Cost %>
    <%= form.number_field :Cost %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mslanes/edit.html.erb
<h1>Editing Mslane</h1>

<%= render 'form', mslane: @mslane %>

<%= link_to 'Show', @mslane %> |
<%= link_to 'Back', mslanes_path %>

app/views/mslanes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mslanes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Release</th>
      <th>Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mslanes.each do |mslane| %>
      <tr>
        <td><%= mslane.Title %></td>
        <td><%= mslane.Category %></td>
        <td><%= mslane.Release %></td>
        <td><%= mslane.Cost %></td>
        <td><%= link_to 'Show', mslane %></td>
        <td><%= link_to 'Edit', edit_mslane_path(mslane) %></td>
        <td><%= link_to 'Destroy', mslane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mslane', new_mslane_path %>

app/views/mslanes/new.html.erb
<h1>New Mslane</h1>

<%= render 'form', mslane: @mslane %>

<%= link_to 'Back', mslanes_path %>

app/views/mslanes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @mslane.Title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @mslane.Category %>
</p>

<p>
  <strong>Release:</strong>
  <%= @mslane.Release %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @mslane.Cost %>
</p>

<%= link_to 'Edit', edit_mslane_path(@mslane) %> |
<%= link_to 'Back', mslanes_path %>